// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: streaming.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PeticionStream identifica el audio a reproducir. Los datos de título y tipo
// los aporta el cliente porque ya los consultó al servidor de metadata (REST);
// el servidor de streaming solo necesita el id para ubicar audios/<id>.mp3 y
// título/tipo para notificar la reproducción a la cola.
type PeticionStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdAudio     int32  `protobuf:"varint,1,opt,name=id_audio,json=idAudio,proto3" json:"id_audio,omitempty"`
	TituloAudio string `protobuf:"bytes,2,opt,name=titulo_audio,json=tituloAudio,proto3" json:"titulo_audio,omitempty"`
	TipoAudio   string `protobuf:"bytes,3,opt,name=tipo_audio,json=tipoAudio,proto3" json:"tipo_audio,omitempty"`
}

func (x *PeticionStream) Reset() {
	*x = PeticionStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeticionStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeticionStream) ProtoMessage() {}

func (x *PeticionStream) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeticionStream.ProtoReflect.Descriptor instead.
func (*PeticionStream) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *PeticionStream) GetIdAudio() int32 {
	if x != nil {
		return x.IdAudio
	}
	return 0
}

func (x *PeticionStream) GetTituloAudio() string {
	if x != nil {
		return x.TituloAudio
	}
	return ""
}

func (x *PeticionStream) GetTipoAudio() string {
	if x != nil {
		return x.TipoAudio
	}
	return ""
}

// FragmentoAudio es un trozo de bytes del archivo mp3.
type FragmentoAudio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datos      []byte `protobuf:"bytes,1,opt,name=datos,proto3" json:"datos,omitempty"`
	Numero     int32  `protobuf:"varint,2,opt,name=numero,proto3" json:"numero,omitempty"`                           // secuencia del fragmento (desde 1)
	TotalBytes int64  `protobuf:"varint,3,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"` // tamaño total del archivo (para progreso)
}

func (x *FragmentoAudio) Reset() {
	*x = FragmentoAudio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_streaming_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FragmentoAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentoAudio) ProtoMessage() {}

func (x *FragmentoAudio) ProtoReflect() protoreflect.Message {
	mi := &file_streaming_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentoAudio.ProtoReflect.Descriptor instead.
func (*FragmentoAudio) Descriptor() ([]byte, []int) {
	return file_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *FragmentoAudio) GetDatos() []byte {
	if x != nil {
		return x.Datos
	}
	return nil
}

func (x *FragmentoAudio) GetNumero() int32 {
	if x != nil {
		return x.Numero
	}
	return 0
}

func (x *FragmentoAudio) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

var File_streaming_proto protoreflect.FileDescriptor

var file_streaming_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x22, 0x6d, 0x0a, 0x0e,
	0x50, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x19,
	0x0a, 0x08, 0x69, 0x64, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x69, 0x64, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x74,
	0x75, 0x6c, 0x6f, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x74, 0x69, 0x74, 0x75, 0x6c, 0x6f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x69, 0x70, 0x6f, 0x5f, 0x61, 0x75, 0x64, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x69, 0x70, 0x6f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x22, 0x5f, 0x0a, 0x0e, 0x46,
	0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x6f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x61, 0x74, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x64, 0x61,
	0x74, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x32, 0x5a, 0x0a, 0x11,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x69, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e,
	0x67, 0x12, 0x45, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x12, 0x19, 0x2e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x65, 0x74,
	0x69, 0x63, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x19, 0x2e, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x46, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x6f, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_streaming_proto_rawDescOnce sync.Once
	file_streaming_proto_rawDescData = file_streaming_proto_rawDesc
)

func file_streaming_proto_rawDescGZIP() []byte {
	file_streaming_proto_rawDescOnce.Do(func() {
		file_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(file_streaming_proto_rawDescData)
	})
	return file_streaming_proto_rawDescData
}

var file_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_streaming_proto_goTypes = []any{
	(*PeticionStream)(nil), // 0: streaming.PeticionStream
	(*FragmentoAudio)(nil), // 1: streaming.FragmentoAudio
}
var file_streaming_proto_depIdxs = []int32{
	0, // 0: streaming.ServicioStreaming.StreamAudio:input_type -> streaming.PeticionStream
	1, // 1: streaming.ServicioStreaming.StreamAudio:output_type -> streaming.FragmentoAudio
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_streaming_proto_init() }
func file_streaming_proto_init() {
	if File_streaming_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_streaming_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PeticionStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_streaming_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FragmentoAudio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_streaming_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_streaming_proto_goTypes,
		DependencyIndexes: file_streaming_proto_depIdxs,
		MessageInfos:      file_streaming_proto_msgTypes,
	}.Build()
	File_streaming_proto = out.File
	file_streaming_proto_rawDesc = nil
	file_streaming_proto_goTypes = nil
	file_streaming_proto_depIdxs = nil
}
