// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: streaming.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	ServicioStreaming_StreamAudio_FullMethodName = "/streaming.ServicioStreaming/StreamAudio"
)

// ServicioStreamingClient is the client API for ServicioStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicioStreamingClient interface {
	// Server-streaming: el servidor envía el audio en fragmentos (chunks).
	StreamAudio(ctx context.Context, in *PeticionStream, opts ...grpc.CallOption) (ServicioStreaming_StreamAudioClient, error)
}

type servicioStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewServicioStreamingClient(cc grpc.ClientConnInterface) ServicioStreamingClient {
	return &servicioStreamingClient{cc}
}

func (c *servicioStreamingClient) StreamAudio(ctx context.Context, in *PeticionStream, opts ...grpc.CallOption) (ServicioStreaming_StreamAudioClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ServicioStreaming_ServiceDesc.Streams[0], ServicioStreaming_StreamAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &servicioStreamingStreamAudioClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServicioStreaming_StreamAudioClient interface {
	Recv() (*FragmentoAudio, error)
	grpc.ClientStream
}

type servicioStreamingStreamAudioClient struct {
	grpc.ClientStream
}

func (x *servicioStreamingStreamAudioClient) Recv() (*FragmentoAudio, error) {
	m := new(FragmentoAudio)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ServicioStreamingServer is the server API for ServicioStreaming service.
// All implementations must embed UnimplementedServicioStreamingServer
// for forward compatibility
type ServicioStreamingServer interface {
	// Server-streaming: el servidor envía el audio en fragmentos (chunks).
	StreamAudio(*PeticionStream, ServicioStreaming_StreamAudioServer) error
	mustEmbedUnimplementedServicioStreamingServer()
}

// UnimplementedServicioStreamingServer must be embedded to have forward compatible implementations.
type UnimplementedServicioStreamingServer struct {
}

func (UnimplementedServicioStreamingServer) StreamAudio(*PeticionStream, ServicioStreaming_StreamAudioServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedServicioStreamingServer) mustEmbedUnimplementedServicioStreamingServer() {}

// UnsafeServicioStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicioStreamingServer will
// result in compilation errors.
type UnsafeServicioStreamingServer interface {
	mustEmbedUnimplementedServicioStreamingServer()
}

func RegisterServicioStreamingServer(s grpc.ServiceRegistrar, srv ServicioStreamingServer) {
	s.RegisterService(&ServicioStreaming_ServiceDesc, srv)
}

func _ServicioStreaming_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PeticionStream)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServicioStreamingServer).StreamAudio(m, &servicioStreamingStreamAudioServer{ServerStream: stream})
}

type ServicioStreaming_StreamAudioServer interface {
	Send(*FragmentoAudio) error
	grpc.ServerStream
}

type servicioStreamingStreamAudioServer struct {
	grpc.ServerStream
}

func (x *servicioStreamingStreamAudioServer) Send(m *FragmentoAudio) error {
	return x.ServerStream.SendMsg(m)
}

// ServicioStreaming_ServiceDesc is the grpc.ServiceDesc for ServicioStreaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicioStreaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.ServicioStreaming",
	HandlerType: (*ServicioStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _ServicioStreaming_StreamAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streaming.proto",
}
