// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: streaming.proto

package serviciosAudio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AudioService_AudioStream_FullMethodName = "/servicios.AudioService/AudioStream"
)

// AudioServiceClient is the client API for AudioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioServiceClient interface {
	// Streaming de audio: el servidor devuelve un flujo de fragmentos
	AudioStream(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (AudioService_AudioStreamClient, error)
}

type audioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioServiceClient(cc grpc.ClientConnInterface) AudioServiceClient {
	return &audioServiceClient{cc}
}

func (c *audioServiceClient) AudioStream(ctx context.Context, in *AudioRequest, opts ...grpc.CallOption) (AudioService_AudioStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioService_ServiceDesc.Streams[0], AudioService_AudioStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &audioServiceAudioStreamClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AudioService_AudioStreamClient interface {
	Recv() (*AudioChunk, error)
	grpc.ClientStream
}

type audioServiceAudioStreamClient struct {
	grpc.ClientStream
}

func (x *audioServiceAudioStreamClient) Recv() (*AudioChunk, error) {
	m := new(AudioChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AudioServiceServer is the server API for AudioService service.
// All implementations must embed UnimplementedAudioServiceServer
// for forward compatibility
type AudioServiceServer interface {
	// Streaming de audio: el servidor devuelve un flujo de fragmentos
	AudioStream(*AudioRequest, AudioService_AudioStreamServer) error
	mustEmbedUnimplementedAudioServiceServer()
}

// UnimplementedAudioServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAudioServiceServer struct {
}

func (UnimplementedAudioServiceServer) AudioStream(*AudioRequest, AudioService_AudioStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method AudioStream not implemented")
}
func (UnimplementedAudioServiceServer) mustEmbedUnimplementedAudioServiceServer() {}

// UnsafeAudioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioServiceServer will
// result in compilation errors.
type UnsafeAudioServiceServer interface {
	mustEmbedUnimplementedAudioServiceServer()
}

func RegisterAudioServiceServer(s grpc.ServiceRegistrar, srv AudioServiceServer) {
	s.RegisterService(&AudioService_ServiceDesc, srv)
}

func _AudioService_AudioStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AudioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AudioServiceServer).AudioStream(m, &audioServiceAudioStreamServer{ServerStream: stream})
}

type AudioService_AudioStreamServer interface {
	Send(*AudioChunk) error
	grpc.ServerStream
}

type audioServiceAudioStreamServer struct {
	grpc.ServerStream
}

func (x *audioServiceAudioStreamServer) Send(m *AudioChunk) error {
	return x.ServerStream.SendMsg(m)
}

// AudioService_ServiceDesc is the grpc.ServiceDesc for AudioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicios.AudioService",
	HandlerType: (*AudioServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AudioStream",
			Handler:       _AudioService_AudioStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "streaming.proto",
}
